
//BEFORE THE BACKEND 
export const mockFlights = [
  {
    id: 1,
    company: "AeroTransit",
    origin: "Paris",
    destination: "London",
    departureDate: "2025-11-25",
    departure: "08:00",
    arrival: "09:15",
    price: 120,
  },
  {
    id: 2,
    company: "AeroTransit",
    origin: "Paris",
    destination: "London",
    departureDate: "2025-11-25",
    departure: "14:00",
    arrival: "15:15",
    price: 145,
  },
  {
    id: 3,
    company: "AeroTransit",
    origin: "London",
    destination: "Paris",
    departureDate: "2025-11-26",
    departure: "09:00",
    arrival: "10:15",
    price: 110,
  },
  {
    id: 4,
    company: "AeroTransit",
    origin: "New York",
    destination: "Paris",
    departureDate: "2025-12-01",
    departure: "18:00",
    arrival: "07:00",
    price: 450,
  },
  {
    id: 5,
    company: "AeroTransit",
    origin: "Paris",
    destination: "New York",
    departureDate: "2025-12-10",
    departure: "10:00",
    arrival: "13:00",
    price: 480,
  },
  {
    id: 6,
    company: "AeroTransit",
    origin: "Dubai",
    destination: "London",
    departureDate: "2025-11-25",
    departure: "02:00",
    arrival: "06:30",
    price: 600,
  },
];
